services:
  frontend:
    build:
      context: ./employees-frontend
    ports:
      - "4200:80"  
    depends_on:
      - backend

  backend:
    build:
      context: ./employess-backend
    ports:
      - "8080:8080"
